jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dev_sung
      path: 'jaffle_shop.duckdb'

    prod:
      type: duckdb
      schema: prod_sung
      path: 'jaffle_shop.duckdb'
