jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dev_sung
      path: 'jaffle_shop.duckdb'
      threads: 16

    prod:
      type: duckdb
      schema: prod_sung
      path: 'md:jaffle_shop'
      threads: 16

    insane_o_style:
      type: duckdb
      schema: insane_o_style
      path: 'md:jaffle_shop'
      threads: 16

    neon:
      type: postgres
      host: "{{ env_var('HOST') }}"
      # host: ep-shrill-meadow-043325-pooler.us-west-2.aws.neon.tech
      user: "{{ env_var('ROLE') }}"
      password: "{{ env_var('PASSWORD') }}"
      port: 5432 # The default PostgreSQL port
      dbname: "{{ env_var('DBNAME') }}"
      schema: dbt_sung_dev # Default schema for PostgreSQL
      threads: 24 # Choose the appropriate number
      connect_timeout: 10 # default 10 seconds
      sslmode: require
