jaffle_shop:
  # sqlmesh will reuse the database and schema config for databricks
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: WXB73651
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: accountadmin # highly recommend creating a least privileges role
      database: migrate_demo # replace with an existing database or use your own profiles.yml config
      warehouse: COMPUTE_WH
      schema: new_life_ahead # name this whatever you want :)
      threads: 16
      client_session_keep_alive: True

    databricks:
      type: databricks
      catalog: migrate_demo #optional catalog name if you are using Unity Catalog]
      schema: new # Required
      host: "{{ env_var('DATABRICKS_SERVER_HOSTNAME') }}" # Required
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"# Required
      token: "{{ env_var('DATABRICKS_ACCESS_TOKEN') }}" # Required Personal Access Token (PAT) if using token-based authentication
      threads: 16  # Optional, default 1

    bigquery:
      type: bigquery
      method: service-account
      project: sqlmesh-public-demo
      dataset: dbt_to_sqlmesh_migrate_demo
      threads: 16 # Must be a value of 1 or greater
      keyfile: service-account.json