jaffle_shop:
  # sqlmesh will reuse the database and schema config for databricks
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: WXB73651
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: accountadmin # highly recommend creating a least privileges role
      database: migrate_demo
      warehouse: COMPUTE_WH
      schema: new_future
      threads: 16
      client_session_keep_alive: True

    # databricks:
    #   type: databricks
    #   catalog: migrate_demo #optional catalog name if you are using Unity Catalog]
    #   schema: new # Required
    #   host: dbc-b9f590c4-0a08.cloud.databricks.com # Required
    #   http_path: /sql/protocolv1/o/5705746990502068/0603-211256-ns7ii2e2 # Required
    #   token: "{{ env_var('DATABRICKS_ACCESS_TOKEN') }}" # Required Personal Access Token (PAT) if using token-based authentication
    #   threads: 16  # Optional, default 1

    bigquery:
      type: bigquery
      method: service-account
      project: sqlmesh-public-demo
      dataset: dbt_to_sqlmesh_migrate_demo
      threads: 16 # Must be a value of 1 or greater
      keyfile: service-account.json