jaffle_shop:

  target: databricks
  outputs:
    snowflake:
      type: snowflake
      account: WXB73651
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: accountadmin
      database: DBT_TO_SQLMESH_DEMO
      warehouse: COMPUTE_WH
      schema: old
      threads: 16
      client_session_keep_alive: True

    databricks:
      type: databricks
      catalog: public_demo #optional catalog name if you are using Unity Catalog]
      schema: new # Required
      host: dbc-b9f590c4-0a08.cloud.databricks.com # Required
      http_path: /sql/protocolv1/o/5705746990502068/0603-211256-ns7ii2e2 # Required
      token: "{{ env_var('DATABRICKS_ACCESS_TOKEN') }}" # Required Personal Access Token (PAT) if using token-based authentication
      threads: 16  # Optional, default 1